name: Healthcheck
author: Rüdiger Schulz
description: Check connection to a single URL
branding:
    color: red
    icon: heart
inputs:
    url:
        description: URL to connect to
        required: true
    retries:
        description: Number of retries before failing
        required: false
        default: '5'
    username:
        description: Username for basic auth
        required: false
    password:
        description: Password for basic auth
        required: false
runs:
    using: docker
    image: Dockerfile
    args:
        - ${{ inputs.url }}
        - ${{ inputs.retries }}
        - ${{ inputs.username }}
        - ${{ inputs.password }}
        